# v1.3.0. Created based on golangci-lint v1.57.0

run:
  timeout: 5m
  concurrency: 0
  modules-download-mode: readonly
  allow-serial-runners: true

output:
  sort-results: true
  uniq-by-line: false

linters-settings:
  depguard:
    rules:
      all:
        list-mode: lax
        deny:
          - pkg: "flag"
            desc: '`flag` package is only allowed in main.go'
          - pkg: "log$"
            desc: 'logging is provided by `log/slog`'
          - pkg: "io/ioutil"
            desc: '`io/ioutil` package is deprecated, use the `io` and `os` package instead'
          - pkg: "reflect"
            desc: '`reflect` package is dangerous to use'
          - pkg: "unsafe"
            desc: '`unsafe` package is dangerous to use'

  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

  errchkjson:
    report-no-exported: true

  exhaustive:
    check-generated: true
    default-signifies-exhaustive: true

  forbidigo:
    forbid:
      - ^panic$
      - ^print(ln)?$
      - ^fmt\.Print(f|ln)?$
      - ^http\.Default(Client|ServeMux|Transport)$
      - ^time\.Sleep$
    analyze-types: true

  gci:
    sections:
      - standard
      - prefix(github.com/leonklingele/tldwatch)
      - default
      - blank
      - dot
      # - alias
    custom-order: true

  goconst:
    numbers: true

  gocritic:
    enable-all: true
    disabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      underef:
        skipRecvDeref: false
      # NOTE: Set this option to false if other projects rely on this project's code
      unnamedResult:
        checkExported: true

  gofumpt:
    module-path: github.com/leonklingele/tldwatch
    extra-rules: true

  gosec:
    config:
      global:
        show-ignored: true
        audit: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  grouper:
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: true
    # var-require-grouping: true # TODO: Conflicts with gofumpt

  loggercheck:
    require-string-key: true
    no-printf-like: true

  misspell:
    locale: US

  nolintlint:
    require-explanation: true
    require-specific: true

  nonamedreturns:
    report-error-in-defer: true

  perfsprint:
    err-error: true

  predeclared:
    q: true

  promlinter:
    strict: true

  reassign:
    patterns:
      - '.*'

  revive:
    enable-all-rules: true
    rules:
      # Provided by gomnd linter
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      # Provided by bidichk
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: comment-spacings
        arguments:
          - nolint
      - name: cyclomatic
        disabled: true
      # TODO: Enable this check. Currently disabled due to upstream bug.
      # - name: enforce-repeated-arg-type-style
      #   arguments:
      #     - short
      - name: enforce-slice-style
        arguments:
          - make
      - name: exported
        disabled: true
      - name: file-header
        disabled: true
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: modifies-parameter
        disabled: true
      - name: package-comments
        disabled: true
      - name: optimize-operands-order
        disabled: true

  sloglint:
    kv-only: true
    no-global: "all"
    args-on-sep-lines: true

  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1020
      - -ST1021
      - -ST1022

  tagalign:
    strict: true

  tagliatelle:
    case:
      rules:
        json: snake

  tenv:
    all: true

  testifylint:
    enable-all: true

  testpackage:
    skip-regexp: "^$"

  unparam:
    # NOTE: Set this option to false if other projects rely on this project's code
    check-exported: true

  unused:
    parameters-are-used: false
    local-variables-are-used: false
    # NOTE: Set these options to true if other projects rely on this project's code
    field-writes-are-uses: false
    # exported-is-used: false # TODO: Fix issues with this option (upstream)
    exported-fields-are-used: false

  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    os-dev-null: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
    syslog-priority: true

issues:
  exclude-use-default: false
  exclude-dirs-use-default: false
  exclude-case-sensitive: true
  exclude-generated-strict: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - goerr113
      text: 'do not define dynamic errors, use wrapped static errors instead*'
  # fix: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct
    # - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    - goerr113
    - gofmt
    - gofumpt
    # - goheader
    # - goimports
    # - golint
    - gomnd
    - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - ifshort
    # - importas
    # - inamedparam
    - ineffassign
    # - interfacebloat
    # - interfacer
    - intrange
    # - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    # - maligned
    - mirror
    - misspell
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    - perfsprint
    # - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - scopelint
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint
